# Generated by Django 5.0.1 on 2024-02-08 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberbusiness',
            name='location',
        ),
        migrations.RemoveField(
            model_name='memberproporty',
            name='location',
        ),
    ]
