# Generated by Django 5.0.1 on 2024-02-13 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_memberbusiness_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='code',
        ),
    ]
