# Generated by Django 5.0.1 on 2024-02-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_member_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_head',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
