# Generated by Django 5.0.1 on 2024-05-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_memberfimaly_memberfamily_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='Profile QR Code'),
        ),
    ]
